config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :users do
    resources :auctions do
      resources :bids
    end
    get "/bids" => "users#bids"
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :auction
  belongs_to :user
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize_owner, only: [:edit, :destroy]
  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    auction = Auction.find params[:auction_id]
    if auction.user == current_user
      redirect_to root_path, notice: "WTF???"
    else
      if params["bid"]["bid_price"].to_i > Bid.where(auction_id: auction.id).order(bid_price: :desc).first.bid_price
        bid_date = Date.today
        @bid = Bid.new(bid_price: params["bid"]["bid_price"].to_i, bid_date: bid_date)
        @bid.auction = auction
        @bid.user = User.find params[:user_id]
        respond_to do |format|
          if @bid.save
            if params["bid"]["bid_price"].to_i >= auction.reserve_price
              auction.meet_reserve
              auction.save
            end
            format.html { redirect_to user_auction_path(@bid.user, @bid.auction), notice: 'Bid was successfully created.' }
            format.json { render :show, status: :created, location: @bid }
          else
            format.html { render :new }
            format.json { render json: @bid.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to user_auction_path(current_user, auction), notice: "Bid higher!"
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid, url: user_auction_bids_path(current_user, @auction), html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @bid.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h4>

      <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :bid_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :bid_price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bids/edit.html.erb
<div class="page-header">
  <%= link_to bids_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @bid, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing bid</h1>
</div>

<%= render 'form' %>

app/views/bids/index.html.erb
<div class="page-header">
  <%= link_to new_bid_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Bid
  <% end %>
  <h1>Listing bids</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Bid price</th>
            <th>Auction</th>
            <th>Bid date</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @bids) do |bid| %>
            <td><%= bid.bid_price %></td>
            <td><%= bid.auction %></td>
            <td><%= bid.bid_date %></td>
            <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bids/new.html.erb
<div class="page-header">
  <%= link_to bids_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New bid</h1>
</div>

<%= render 'form' %>

app/views/bids/show.html.erb
<div class="page-header">
  <%= link_to bids_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_bid_path(@bid), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show bid</h1>
</div>

<dl class="dl-horizontal">
  <dt>Bid price:</dt>
  <dd><%= @bid.bid_price %></dd>

  <dt>Auction:</dt>
  <dd><%= @bid.auction %></dd>

  <dt>Bid date:</dt>
  <dd><%= @bid.bid_date %></dd>

</dl>