config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :users do
    resources :auctions do
      resources :bids
    end
    get "/bids" => "users#bids"
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_many :bids, dependent: :destroy
  belongs_to :user

  include AASM

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :reserve_met
    state :won
    state :canceled
    state :reserve_not_met

    event :submit do
      transitions from: :draft, to: :published
    end

    event :meet_reserve do
      transitions from: :published, to: :reserve_met
    end

    event :win do
      transitions from: :reserve_met, to: :won
    end

    event :cancel do
      transitions from: [:published, :reserve_met, :reserve_not_met], to: :canceled
    end

    event :fail do
      transitions from: :published, to: :reserve_not_met
    end
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize_owner, only: [:edit, :destroy]
  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    auction = Auction.find params[:id]
    bids = auction.bids.order(bid_price: :desc)
    bids_info = []
    bids.each do |bid|
      bid_info = {
        id: bid.id,
        bid_price: bid.bid_price,
        bid_date: bid.bid_date,
        user: User.find(bid.user_id).full_name
      }
      bids_info << bid_info
    end
    @bid = Bid.new
    respond_to do |format|
      format.html
      format.json { render json: bids_info}
    end
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    @auction.user = User.find params[:user_id]
    @auction.submit
    respond_to do |format|
      if @auction.save
        format.html { redirect_to user_auction_path(@auction.user_id, @auction), notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to user_auction_path(@auction.user_id, @auction), notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:title, :details, :ends_on, :reserve_price)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<script>
  $(document).ready(function() {
     $("#auction_ends_on").datepicker();
  });
</script>
<style>
.ui-datepicker .ui-widget-content {
    background-color: white;
}
</style>
<%= form_for(@auction, url: user_auctions_path(current_user)) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :ends_on %><br>
    <%= f.text_field :ends_on %>
  </div>
  <div class="field">
    <%= f.label :reserve_price %><br>
    <%= f.number_field :reserve_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Auctions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Ends on</th>
      <th>Reserve price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.title %></td>
        <td><%= auction.details %></td>
        <td><%= auction.ends_on %></td>
        <td><%= auction.reserve_price %></td>
        <td><%= link_to 'Show', user_auction_path(current_user, auction) %></td>
        <td><%= link_to 'Edit', edit_user_auction_path(current_user, auction) %></td>
        <td><%= link_to 'Destroy', user_auction_path(current_user, auction), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Auction', new_user_auction_path(current_user) %>
<% end %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/auctions/show.html.erb
<script>
  $(document).ready(function() {
    var url = $(location).attr("href");
    $.ajax({
      method: "GET",
      url: url + ".json",
      success: function(data) {
        for(var i = 0; i < data.length; i++)
        $('.bids').append("<li> $" + data[i].bid_price + " date: " + data[i].bid_date + " Buyer: " + data[i].user +"</li>")
      }
    })
    $('button').click(function() {
      var bidPrice = parseInt($('#bid-price').val());
      var userId = url.match(/users\/(\d+)/)[1];
      var auctionId = url.match(/auctions\/(\d+)/)[1];
      var currentTime = new Date();
      $.ajax({
        method: "POST",
        url: url + "/bids",
        data: {bid: {bid_price: bidPrice, bid_date: currentTime}},
        success: function(){
          $('.bids').children().first().hide();
          $('.bids').children().first().fadeIn(2000);
       }
      })
    })
  })
</script>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @auction.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @auction.details %>
</p>

<p>
  <strong>Ends on:</strong>
  <%= @auction.ends_on %>
</p>

<p>
  <strong>Reserve price:</strong>
  <%= @auction.reserve_price %>
</p>

<% if @auction.user == current_user %>
  <%= link_to "Publish", "#" %> |
<% end %>
<%= link_to 'Edit', edit_user_auction_path(current_user, @auction) %> |
<%= link_to 'Back', root_path %>
<input type="text" id="bid-price"></input>
<button id="submit-bid">Bid</button>
<div class="bids">
</div>